### PR TITLE
Added editable crud template and some fixes

### PR DESCRIPTION
**Pull request by uldisn**

### CODE REVIEW

**Comment by schmunk42** [comment]
You're currently skipping all related attributes, right?
Is this just because of keeping things rather simple - which absolutely perfect - or were there other reasons behind it?

**Comment by uldisn** [comment]
No, I use related attributes editable crud. Only in ediatble fields is work like listbox.

**Comment by schmunk42** [comment]
Why did you close the PR?

**Comment by uldisn** [comment]
I do some changes in my private template and no testing, how it affect public editable crud template.

**Comment by schmunk42** [comment]
I didn't tried your changes yet, because the PR was closed.
I'd really like to see the editable feature in Giiant.

What do you think, is it basically working - a new feature like that might have issues - but we're still in beta for 0.9.0. 

Or are the real bugs, blockers or issues at the moment? Code looked good to me on first sight.

**Comment by schmunk42** [comment]
Let me know when I can give this a try...

**Comment by uldisn** [comment]
I finished.

**Comment by schmunk42** [comment]
Thank you!

I merged it here https://github.com/schmunk42/yii2-giiant/tree/feature/editable and tried it in a project and it was working with a few layout glitches. 👍 

A few questions ... 
- would it be possible to remove kartik/grid, it requires kartik/yii2-mpdf, which requires a huge repo kartik/mpdf; just keep the editable
- why do you need to load $_GET params for create and update?
- there are changes to the DateProvider, is this required for editable?
- could you try running the test with docker?

In general, if possible an implementation of new feature via traits would be nice - but it's sometimes hard to do.

**Comment by schmunk42** [comment]
Just for the record, I needed those:

-    "kartik-v/yii2-grid": "^3.1",
-    "kartik-v/yii2-editable": "^1.7",
-    "kartik-v/yii2-mpdf": "^1.0"

**Comment by uldisn** [comment]
Answers on questions
- kartik/grid used in editable view for related table items grid
-  load $_GET create & update for case, when create or update related item. In $_GET store main table PK. This PK  value set in form field and set this field as read only.
- Dateprovider used in editable crud, when creating new record use input form. I have problems with date formats and partly solved.
 - I do not use dockers. Sorry!

In Yii2 editable solution more complex as in Yii.

**Comment by schmunk42** [comment]
> kartik/grid used in editable view for related table items grid. I do not see alternatives.

This is mainly because of the EditableColumn, right? Can't it be used in a normal grid?

> load $_GET create & update for case, when create or update related item. In $_GET store main table PK. This PK value set in form field and set this field as read only. That also work in default crud template.

I don't quite understand. Do you need this to go back to the original item?

> Dateprovider used in editable crud, when creating new record use input form. I have problems with date formats and partly solved.

FYI: I splitted the providers into core and extension providers.

> I do not use dockers. Sorry!

You should [give it a try](https://docs.docker.com/engine/installation/windows/#/docker-for-windows), it's really great for testing giiant.

**Comment by schmunk42** [comment]
Why are there changes to the default template? You mentioned the parameters above, but I understand how they are supposed to work.

**Comment by uldisn** [comment]
- Kartik EditableColumn do not work in normal grid.
 - By $_GET transport form field values. Currently main table PK value, but can use for other fields. Additionally disable for editing this fields.

**Pull request merged**
