### PR TITLE
use single quotes and fix spacing for consistancy

### PR DESCRIPTION
**Pull request by cornernote**

### CODE REVIEW

**Comment by cornernote** [comment]
it makes the generator put things the same way storm does, so there is no change if you do a file cleanup (ctrl+alt+L in storm)

i also edited the templates to achieve this in other places, but they are different to yours now, so i wont PR those

**Comment by cornernote** [comment]
relates to #33

**Comment by cornernote** [comment]
Will break this into smaller PRs so some can be pushed through.

**Comment by schmunk42** [comment]
merged other PRs

**Pull request closed without merging**
