### PR TITLE
improve indentation of columns inside GridView

### PR DESCRIPTION
**Pull request by cornernote**
this indents the columns to where they should be when nesting them inside the GridView (both the columns and GridView are rendered by the same method, so the indentation level is known)

### CODE REVIEW

**Comment by schmunk42** [comment]
Functions should not return with indent, we need another solution for that.

**Comment by cornernote** [comment]
Ok, I put my argument forward, and it seems to have been misunderstood or ignored.  Might as well not indent anything.

**Comment by cornernote** [comment]
my way:
```php
$cleanCode <<<EOF
    echo implode(', ', [
        'code will be simple to indent';
    ]);
EOF;

if ($indentWhereYouKknowTheIndentationLevel) {
$cleanCode;
}
```

my result:
```php
if ($indentWhereYouKknowTheIndentationLevel) {
    echo implode(', ', [
        'code will be simple to indent';
    ]);
}
```

your way:
```php
$cleanCode <<<EOF
echo implode(', ', [
    'code will be difficult to indent';
]);
EOF;

if ($noIndentWhereYouKknowTheIndentationLevel) {
$cleanCode;
}
```

your result:
```php
if ($indentWhereYouKknowTheIndentationLevel) {
echo implode(', ', [
    'code will be difficult to indent';
]);
}
```

**Comment by schmunk42** [comment]
It's not ignored and I know what the goal is .... *searching the web*

OK, here's a real candidate: https://github.com/cmrcx/phptidy

I just tried this on a large project and it looks awesome!
Could you review and try the `phptidy` script?

**Pull request closed without merging**
