### PR TITLE
Implement ReturnUrl

### PR DESCRIPTION
**Pull request by fredyns**
following up #86 

Personally, i'd like to put ReturnUrl in crud template too.
improve navigation in multitab operation.

### CODE REVIEW

**Comment by fredyns** [comment]
whoa.. local test is passing smootly.
did i do it wrong?

**Comment by schmunk42** [comment]
Local Docker tests oder manual tests? 

You can see the test log by clicking on the :x: beside the commit hash and then *Details* - https://travis-ci.org/schmunk42/yii2-giiant/builds/166121233

It may also be an issue that there's no `cornernote/yii2-returnurl` in the testing app. I'll reopen and review.

**Comment by schmunk42** [comment]
Hmm, I get this error in local Docker tests

```
PHP Fatal Error – yii\base\ErrorException

Class 'cornernote\returnurl\ReturnUrl' not found
```

despite the fact that I actually installed the extension via `tests/_build/composer.*`and rebuilt the image, need to investigate....?!

**Comment by fredyns** [comment]
i had repeat the test locally & saw the error too.

i still trying (learning) on it.

**Comment by fredyns** [comment]
i'm still trying to do this, but still failed.

it pass CliTester, ReturnUrl class & file exist when running batch generator.
but not passing AcceptanceTester,  class & file didn't even exist.

**Comment by schmunk42** [comment]
We've removed this feature.

**Pull request closed without merging**
