### PR TITLE
Providers can define in config of giant-grud providerList parameter

### PR DESCRIPTION
**Pull request by uldisn**

### CODE REVIEW

**Comment by schmunk42** [comment]
Could you split this up a little bit. As far as I can see, there are changes to the 

- saved form attributes (tests are failing because of that btw).
- providers
- new parameter `providerListPostHidded` - do know what it does atm, but should read `providerListPostHidden` I think.

**Comment by schmunk42** [comment]
@uldisn Could you try to run & check the test suite, it's failing in the PR.

**Comment by uldisn** [comment]
Tomorrow.

**Comment by schmunk42** [comment]
Sorry for taking so long, ... but tests are not passing, closing for now.

**Pull request closed without merging**
