### PR TITLE
Allow configuration of ModelGenerator in BatchController

### PR DESCRIPTION
**Pull request by rhertogh**

### CODE REVIEW

**Comment by schmunk42** [comment]
Sorry, missed this. Should it be merged?

**Comment by rhertogh** [comment]
> Sorry, missed this. Should it be merged?

I solved it via the dependency injection, so there is a workaround. The way of crating the object in this PR is more the Yii2 way, so if you are interested I could recreate the PR?

**Comment by schmunk42** [comment]
Yeah, I like it, since it's more Yii2-style.

**Comment by rhertogh** [comment]
@schmunk42 Recreated as #283

**Pull request closed without merging**
