### PR TITLE
Fix singularEntities not working when using cli

### PR DESCRIPTION
**Pull request by liasica**
Hi @schmunk42 
I found one bug of the setting singularEntities is not working after your last update. :)

### CODE REVIEW

**Comment by liasica** [comment]
Oh, eh... that's not right.

**Comment by liasica** [comment]
:) I think right now ~ @schmunk42

**Comment by schmunk42** [comment]
Related to https://github.com/schmunk42/yii2-giiant/pull/227 :(
We need some tests for this.

**Comment by liasica** [comment]
when we use command `./yii batch/models` and set `singularEntities` to `ture`, table `users` generate `Users` model. :(

**Comment by schmunk42** [comment]
Thank you!

**Pull request merged**
