### PR TITLE
Use XxxSearch instead of Xxx as search model

### PR DESCRIPTION
**Pull request by cornernote**
This seems to be the way the default Gii is doing it.

What are your thoughts on this?

### CODE REVIEW

**Comment by schmunk42** [comment]
Should be easily adjustable by the command param.

**Comment by cornernote** [comment]
You can't change it in the batch controller without overriding.

**Comment by schmunk42** [comment]
I see, hmm. Let's postpone that one for now.

**Comment by thadudexx** [comment]
+1

**Comment by schmunk42** [comment]
Thanks!

**Pull request merged**
