### PR TITLE
check for relation link before reset

### PR DESCRIPTION
**Pull request by cornernote**

### CODE REVIEW

**Comment by schmunk42** [comment]
What was the issue behind it?

**Comment by cornernote** [comment]
It was throwing an exception, but I can't seem to re-create it now.

**Comment by cornernote** [comment]
Here we go:

```
root@test:/vagrant/myapp# ./yii gii-tools-batch --tables=client_code
Running full giiant batch...
Running 'Giiant Model'...

The following files will be generated:
  [unchanged] models/base/ClientCode.php

No files were chosen to be generated.
Running 'Giiant CRUD'...

PHP Warning 'yii\base\ErrorException' with message 'reset() expects parameter 1 to be array, null given'

in /vagrant/myapp/vendor/schmunk42/yii2-giiant/crud/Generator.php:236

Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleError(2, 'reset() expects...', '/vagrant/atlant...', 236, Array)
#1 /vagrant/myapp/vendor/schmunk42/yii2-giiant/crud/Generator.php(236): reset(NULL)
#2 /vagrant/myapp/vendor/schmunk42/yii2-giiant/crud/providers/RelationProvider.php(144): schmunk42\giiant\crud\Generator->getRelationByColumn(Object(app\models\Job), Object(yii\db\ColumnSchema))
#3 /vagrant/myapp/vendor/cornernote/yii2-gii-tools/giiant/crud/providers/RelationProvider.php(14): schmunk42\giiant\crud\providers\RelationProvider->columnFormat(Object(yii\db\ColumnSchema), Object(app\models\Job))
#4 [internal function]: cornernote\giitools\giiant\crud\providers\RelationProvider->columnFormat(Object(yii\db\ColumnSchema), Object(app\models\Job))
#5 /vagrant/myapp/vendor/schmunk42/yii2-giiant/crud/Generator.php(500): call_user_func_array(Array, Array)
#6 /vagrant/myapp/vendor/schmunk42/yii2-giiant/crud/Generator.php(366): schmunk42\giiant\crud\Generator->callProviderQueue('columnFormat', Object(yii\db\ColumnSchema), Object(app\models\Job))
#7 /vagrant/myapp/vendor/schmunk42/yii2-giiant/crud/providers/RelationProvider.php(273): schmunk42\giiant\crud\Generator->columnFormat(Object(yii\db\ColumnSchema), Object(app\models\Job))
#8 /vagrant/myapp/vendor/cornernote/yii2-gii-tools/giiant/crud/providers/RelationProvider.php(29): schmunk42\giiant\crud\providers\RelationProvider->relationGrid('Jobs', Object(app\models\query\JobQuery), false)
#9 [internal function]: cornernote\giitools\giiant\crud\providers\RelationProvider->relationGrid('Jobs', Object(app\models\query\JobQuery), false)
#10 /vagrant/myapp/vendor/schmunk42/yii2-giiant/crud/Generator.php(500): call_user_func_array(Array, Array)
#11 /vagrant/myapp/vendor/schmunk42/yii2-giiant/crud/Generator.php(391): schmunk42\giiant\crud\Generator->callProviderQueue('relationGrid', 'Jobs', Object(app\models\query\JobQuery), false)
#12 /vagrant/myapp/vendor/cornernote/yii2-gii-tools/giiant/crud/gii-tools/views/view.php(139): schmunk42\giiant\crud\Generator->relationGrid('Jobs', Object(app\models\query\JobQuery), false)
#13 /vagrant/myapp/vendor/yiisoft/yii2/base/View.php(325): require('/vagrant/atlant...')
#14 /vagrant/myapp/vendor/yiisoft/yii2/base/View.php(247): yii\base\View->renderPhpFile('/vagrant/atlant...', Array)
#15 /vagrant/myapp/vendor/yiisoft/yii2-gii/Generator.php(317): yii\base\View->renderFile('/vagrant/atlant...', Array, Object(schmunk42\giiant\crud\Generator))
#16 /vagrant/myapp/vendor/yiisoft/yii2-gii/generators/crud/Generator.php(173): yii\gii\Generator->render('views/view.php')
#17 /vagrant/myapp/vendor/yiisoft/yii2-gii/console/GenerateAction.php(52): yii\gii\generators\crud\Generator->generate()
#18 /vagrant/myapp/vendor/yiisoft/yii2-gii/console/GenerateAction.php(35): yii\gii\console\GenerateAction->generateCode()
#19 [internal function]: yii\gii\console\GenerateAction->run()
#20 /vagrant/myapp/vendor/yiisoft/yii2/base/Action.php(92): call_user_func_array(Array, Array)
#21 /vagrant/myapp/vendor/yiisoft/yii2/base/Controller.php(151): yii\base\Action->runWithParams(Array)
#22 /vagrant/myapp/vendor/yiisoft/yii2/console/Controller.php(91): yii\base\Controller->runAction('giiant-crud', Array)
#23 /vagrant/myapp/vendor/yiisoft/yii2/base/Module.php(455): yii\console\Controller->runAction('giiant-crud', Array)
#24 /vagrant/myapp/vendor/yiisoft/yii2/console/Application.php(161): yii\base\Module->runAction('gii/giiant-crud', Array)
#25 /vagrant/myapp/vendor/cornernote/yii2-gii-tools/commands/BatchController.php(116): yii\console\Application->runAction('gii/giiant-crud', Array)
#26 /vagrant/myapp/vendor/schmunk42/yii2-giiant/commands/BatchController.php(169): cornernote\giitools\commands\BatchController->actionCruds()
#27 [internal function]: schmunk42\giiant\commands\BatchController->actionIndex()
#28 /vagrant/myapp/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)
#29 /vagrant/myapp/vendor/yiisoft/yii2/base/Controller.php(151): yii\base\InlineAction->runWithParams(Array)
#30 /vagrant/myapp/vendor/yiisoft/yii2/console/Controller.php(91): yii\base\Controller->runAction('', Array)
#31 /vagrant/myapp/vendor/yiisoft/yii2/base/Module.php(455): yii\console\Controller->runAction('', Array)
#32 /vagrant/myapp/vendor/yiisoft/yii2/console/Application.php(161): yii\base\Module->runAction('gii-tools-batch', Array)
#33 /vagrant/myapp/vendor/yiisoft/yii2/console/Application.php(137): yii\console\Application->runAction('gii-tools-batch', Array)
#34 /vagrant/myapp/vendor/yiisoft/yii2/base/Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request))
#35 /vagrant/myapp/yii(22): yii\base\Application->run()
#36 {main}
```

**Comment by cornernote** [comment]
Some more context...

```php
class ClientCode extends \app\models\base\ClientCode
{
    public function getAuditFields()
    {
        return $this->hasMany(AuditField::className(), ['model_id' => 'client_code_id'])->onCondition(['audit_field.model_name' => get_class($this)]);
    }
}
```

```sql
CREATE TABLE `audit_field` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `action` varchar(255) NOT NULL,
  `model_name` varchar(255) NOT NULL,
  `model_id` varchar(255) NOT NULL,
  `field` varchar(255) DEFAULT NULL,
  `old_value` text,
  `new_value` text,
  `user_id` varchar(255) DEFAULT NULL,
  `debug_tag` varchar(255) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_audit_field_action` (`action`),
  KEY `idx_audit_field_model_name` (`model_name`),
  KEY `idx_audit_field_model_id` (`model_id`),
  KEY `idx_audit_field_field` (`field`),
  KEY `idx_audit_field_user_id` (`user_id`),
  KEY `idx_audit_field_debug_tag` (`debug_tag`),
  KEY `idx_audit_field_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `client_code` (
  `client_code_id` int(11) NOT NULL AUTO_INCREMENT,
  `client_id` int(11) DEFAULT NULL,
  `client_code` varchar(255) NOT NULL,
  `client_code_active` tinyint(1) NOT NULL,
  PRIMARY KEY (`client_code_id`),
  UNIQUE KEY `client_id` (`client_id`,`client_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

**Comment by cornernote** [comment]
I remove the `->onCondition(['audit_field.model_name' => get_class($this)])`, but it still throws the same exception.

**Comment by cornernote** [comment]
If I remove the whole `getAuditFields()` method, no exception.

**Comment by cornernote** [comment]
Sorry, forget those last 2 comments... It was a different exception... I'll get more info and report back.

**Comment by cornernote** [comment]
Ok, forget EVERYTHING posted before this... I found the reason...

I have a relation like this:

```
class Job extends \app\models\base\Job
{
    public function getAuditFields()
    {
        return AuditField::find()
            ->orOnCondition(['audit_field.model_id' => $this->job_id, 'audit_field.model_name' => get_class($this)])
            ->orOnCondition(['audit_field.model_id' => ArrayHelper::map($this->getExpenses()->all(), 'expense_id', 'expense_id'), 'audit_field.model_name' => 'app\models\Expense'])
            ->orOnCondition(['audit_field.model_id' => ArrayHelper::map($this->getJobTeches()->all(), 'id', 'id'), 'audit_field.model_name' => 'app\models\JobTech'])
            ->orOnCondition(['audit_field.model_id' => ArrayHelper::map($this->getJobTechCharges()->all(), 'id', 'id'), 'audit_field.model_name' => 'app\models\JobTechCharge'])
            ->orOnCondition(['audit_field.model_id' => ArrayHelper::map($this->getJobTravels()->all(), 'id', 'id'), 'audit_field.model_name' => 'app\models\JobTravel'])
            ->orOnCondition(['audit_field.model_id' => ArrayHelper::map($this->getJobBills()->all(), 'id', 'id'), 'audit_field.model_name' => 'app\models\JobBill'])
            ->orOnCondition(['audit_field.model_id' => ArrayHelper::map($this->getJobBreaks()->all(), 'job_break_id', 'job_break_id'), 'audit_field.model_name' => 'app\models\JobBreak']);

    }
}
```

Removing the relation makes the error go away.  The problem is that this relation doesn't have a link.

The reason I have no link in the relation is explained here:
http://stackoverflow.com/questions/30641503/how-to-define-a-relationship-in-yii2-with-oroncondition

**Pull request merged**
