### PR TITLE
update for skip db tables

### PR DESCRIPTION
**Pull request by liasica**
Skip db tables for generating models

### CODE REVIEW

**Comment by schmunk42** [comment]
So we'd have `tables` for including just certain tables (if defined) or `skipTables` to exclude some tables.

Only one of the params should be used at once I think, should we also issue a warning when both are specified?

CC: @eluhr @handcode WDYT?

**Comment by liasica** [comment]
I have lot of tables in my database, but it's just 2 ~ 3 tables that I need exclude.

It must modify `tables` always when I add new tables, I think it's very inconveniently :)

**Comment by handcode** [comment]
Depending on the application structure, both options can be useful. 

- Usecase for tables[] - applications where most tables come from modules (as in most of our applications)
- Usercase for skipTables[] - see https://github.com/schmunk42/yii2-giiant/pull/226#issuecomment-376120819

But I would only allow one of the two options per giiant run / config-block to minimize the WTF factor.

**Comment by schmunk42** [comment]
Thank you! I will the additional check to avoid both properties set.

**Pull request merged**
